name = "insider-tracker-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "insider-tracker-db"
database_id = "YOUR_DATABASE_ID"  # Will be set after creating D1 database

# Cron trigger for data collection (every 10 minutes)
[triggers]
crons = ["*/10 * * * *"]

# Environment variables
[vars]
ENVIRONMENT = "production"

